### ISSUE TITLE
I typed something in chat and the text came out as if it was from my alt account that was parked 10k away...

### ISSUE THREAD

**Issue by kwizzlehazzizle** [Civcraft/CivChat2#11]
http://imgur.com/DGsO690

Bottler0cket is a bot of mine running on another computer in my house,  He was aroun -5k -5k at the time of the message.

**Comment by ttk2** [comment]
both where online at the same time?

**Comment by idoash4** [comment]
Did it happen yesterday?

@ttk2 Is debugging set to true on civcraft?

**Comment by ttk2** [comment]
yes it is

**Comment by ttk2** [comment]
and yes it did happen yesterday.

**Comment by idoash4** [comment]
Did it happen when the chat range was off? 

Can you post all the debugging information of the message?

**Comment by ttk2** [comment]
not sure when it happened, I don't have good time stamps, but the nubmer of
these errors says they happen pretty normally.

**Comment by idoash4** [comment]
> but the nubmer of these errors says they happen pretty normally.

What errors?

**Comment by ttk2** [comment]
2015-05-19 19:14:57 [INFO] [CivChat2] [Debug] ChatManager.sendPrivateMsg Sender: REDACTED receiver: REDACTED Message: error: variable "q1ans" cannot be nil

**Comment by kwizzlehazzizle** [comment]
Sorry I took so long to reply, 

No, the bug did not happen when the chat range was off.

**Comment by jjj5311** [comment]
this shouldn't be occurring... the error here is cause the chatmessage is null from the event?

@kwizzlehazzizle  if you can get exact time this happened ttk can get the rest of the debug info which will help specificially the Y range info and the chatevent properties

**Comment by ttk2** [comment]
It can't be reproduced. Probably not worth worrying about b

**Comment by suirad** [comment]
Should probably close this for now, if it hasn't resurfaced.

**Comment by ttk2** [comment]
agreed
