### ISSUE TITLE
Ignore group doesn't do anything

### ISSUE THREAD

**Issue by ghost** [Civcraft/CivChat2#17]
http://forum.civcraft.co/t/bug-ignoregroup-doesnt-do-anything/528

**Comment by ttk2** [comment]
oh that's fun, I thought this worked during earlier testing?

**Comment by ghost** [comment]
Not sure. I'm writing a quick test to confirm.

http://forum.civcraft.co/t/open-for-testing-civchat2-ignoregroup-confirm-bug/529

**Comment by jjj5311** [comment]
there should be logs from this that should help... they start with "Checking if player is ignoring group or player.. Receiver:"

**Comment by jjj5311** [comment]
also tested this on civtest this morning and ignoring players and groups is both broken

**Comment by suirad** [comment]
See above pull
