### ISSUE TITLE
Make /say text more imposing

### ISSUE THREAD

**Issue by ghost** [Civcraft/CivChat2#18]
Currently its the same boring old color as any other persons chat text. Want it to be some obvious, attention grabbing color. Pink maybe? Blue? RED? Something visible.

**Comment by suirad** [comment]
What is the difference between /say and a regular global message, other than it being white?

**Comment by ghost** [comment]
/say is an OP only command.

http://minecraft.gamepedia.com/Commands#say

**Comment by suirad** [comment]
Oh so it's pretty much a broadcast.

**Comment by ghost** [comment]
Yup, with civchat2 it's the same color as chat whereas vaniliar it's
more of a blue color.

Any color more visible / imposing would work.

**Comment by jjj5311** [comment]
was this handled differently in the original civchat?

**Comment by ghost** [comment]
IIRC original civchat used vanilla color for /say text

**Comment by jjj5311** [comment]
@drjawa this should be fixed can you confirm?

**Comment by ttk2** [comment]
I think this is corrected. I will try on civtest when I get home.

**Comment by ttk2** [comment]
looking all purple and imposing, closing this issue.
