### ISSUE TITLE
If player tries to message a group they have ignored, server tells them "Unknown command"

### ISSUE THREAD

**Issue by ghost** [Civcraft/CivChat2#20]
I will try to confirm this  when I am awake.

**Comment by jjj5311** [comment]
Just tried this and i don't get any issue with it... with that in mind do we want to let user message a group they are ignoring?

**Comment by ghost** [comment]
Nah. What message do they currently get if they try?

**Comment by jjj5311** [comment]
they just send the message

**Comment by ghost** [comment]
I propbably misspelled a command. If I can't crecreate the issue then
I'll close this.

**Comment by suirad** [comment]
What is the ideal result if a player sends a message to a group they are ignoring? Or should this be closed?

**Comment by ghost** [comment]
Assuming they are ignoring the player or group in question, no message should be sent + they should be told that they need to unignore player/group to send the message.

> or should this be closed?

I haven't confirmed that the original issue exists, but I'll leave it open for now.

**Comment by suirad** [comment]
Addressed in pull: #21
