### ISSUE TITLE
Make Dependent on CivModCore

### ISSUE THREAD

**Issue by rourke750** [Civcraft/CivChat2#25]

**Comment by rourke750** [comment]
@gipsy-king @ProgrammerDan @Xavter @BlackXnt

**Comment by rourke750** [comment]
Also I suppose wait till after 1.8.7 update.

**Comment by ttk2** [comment]
why not just toss the dependency in while upgrading it? 

Also what build do I need for Civtest? the live one does not seem to work anymore there.

**Comment by rourke750** [comment]
Use master.

**Comment by jjj5311** [comment]
I thought suirad updated it already?

**Comment by jjj5311** [comment]
Yeah this is complete it still needs namelayer for groups but the command
stuff is all from civmodcore
