### ISSUE TITLE
/msg "Cannot find a player" that is online

### ISSUE THREAD

**Issue by benjajaja** [Civcraft/CivChat2#27]
`/msg DiRtY_ZeBrA` results in the message "There is no player with that name." in red, and being moved to global chat. Impossible to message that player, tried by several players.

**Comment by ProgrammerDan** [comment]
I feel like a fight club reference would be appropriate here.

**Comment by jjj5311** [comment]
ha, well this is probably a namelayer issue, there must be something funny with his name and/or UUID in the database?

i think the namelayer db needs to be checked 

CivChat just queries NameAPI.getUUID(name) to get a UUID  here https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/CivChat2Manager.java#L351

then trys to get player from Bukkit.getPlayer(UUID) in this method

https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/command/commands/Tell.java#L68

**Comment by ProgrammerDan** [comment]
This is going to be a fun one. Visually I see no problem in the call-stack. @gipsy-king was this on civcraft.co or Civcraft main server?

**Comment by rourke750** [comment]
Also was this yesterday, there might have been some issues going on then
for what ever reason.

**Comment by benjajaja** [comment]
@ProgrammerDan @rourke750 was now on main, after the daily restart. You can still try this yourself as of this writing, zebra is online.

**Comment by ProgrammerDan** [comment]
time to poke at the DB @rourke750  ... :-/

**Comment by erocs** [comment]
He has the correct entry in Name_player. I see a bunch of you guys
attempting to message him half an hour after he logged off. I can see
DiRtY_ZeBrA sending and receiving private messages during that play
session. I'll say user error.

**Comment by benjajaja** [comment]
@erocs he still appears online now, same error. He appears in tab list and the prompt tab-completes his name.

**Comment by benjajaja** [comment]
might by combattag NPC related

**Comment by erocs** [comment]
The scoreboard says that. The server player listing says that. Heck I can
'teleport' to him, but nobody is there. Definitely something weird going on
because by the log entries he very clearly logged off hours ago.

**Comment by ttk2** [comment]
sounds like one of the warnings CombatTag plus gives when using real usernames.

**Comment by benjajaja** [comment]
I'm closing this, which is our combattag repo to report it there?

**Comment by idoash4** [comment]
https://github.com/MinelinkNetwork/CombatTagPlus/issues/33

**Comment by ttk2** [comment]
not sure if that's the actual repo or not.

**Comment by idoash4** [comment]
rourke forked CombatTagPlus from there.
