### ISSUE TITLE
Dependency issue on build server

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivChat2#32]
This has been broken for over a month

http://build.civcraft.co/job/CivChat2-master/

http://build.civcraft.co/job/CivChat2-master/75/console

**Comment by erocs** [comment]
How can it be an issue with the build server when command/commands/Ignore.java doesn't import the class it's attempting to use like command/commands/Tell.java does?  :)

**Comment by Maxopoly** [comment]
Oh yeah, you are right. I didnt really look at the stack, I just stumbled upon it while setting up plugins on civtest and made an issue.

Fixed by https://github.com/Civcraft/CivChat2/commit/df6bd17c1c123046a946a12b0ee6c5383973eedf

**Comment by erocs** [comment]
Thanks for fixing!
