### ISSUE TITLE
Cross server /say command

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#36]
Admins can use /say to send a message as the server, if a message is sent to one shard it should be sent to all shards, or perhaps an alternate command /sayall should be supported so that we can message one shard individually.

**Comment by Maxopoly** [comment]
Working after https://github.com/Civcraft/CivChat2/commit/c3e2d92e45f599003336a6649b3955da468efafd

/say is now to broadcast to a single server, /sayall broadcasts to all servers.
