### ISSUE TITLE
Citadel group chat fails. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/CivChat2#4]

**Comment by jjj5311** [comment]
any more information on this?

**Comment by rourke750** [comment]
There should be a stack trace ttk2?

**Comment by ttk2** [comment]
not seeing one for group chat.

**Comment by jjj5311** [comment]
https://github.com/Civcraft/CivChat2/issues/6

erocs made a new issue with the stack trace i believe

**Comment by GavJenks** [comment]
More information: You type in /groupc [group], it tells you you were moved to that chat, but then when you talk, it still just goes to basic local chat.

**Comment by jjj5311** [comment]
Does it work if you put the message right after groupc

**Comment by GavJenks** [comment]
/groupc [type stuff] -- interprets first word as an intended new group to move to
/groupc [valid group] [additional stuff] -- "an internal error occurred while attempting to perform this command."

Also, while on the subject, please add /g and /gallow as aliases to not confuse people and be more backward compatible.

**Comment by jjj5311** [comment]
ok misplaced an if statement

ill have a pull in a minute
